version: '3'
services:

  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: coffeeshop
      MYSQL_USER: mysql
      DATABASE_HOST: db
      MYSQL_PASSWORD: admin

  web: 
    build: ./web
    environment: 
      DATABASE_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: coffeeshop
      MYSQL_USER: mysql
      MYSQL_PASSWORD: admin
    depends_on:
      - db
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - /c/Users/51676/Desktop/353Project/web:/usr/src/app




