CREATE TABLE menu (
    Item VARCHAR(50) NOT NULL, 
    Price FLOAT
);


CREATE TABLE orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Item VARCHAR(50),
    Price FLOAT,
    OrderTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    OrderStatus VARCHAR(50) DEFAULT 'in progress'
);
